/// The broadcast encryption parameters of a Bluetooth LE accessory server.
///
/// The broadcast encryption key encrypts the payload of encrypted notification
/// advertisements, allowing paired controllers to observe characteristic changes without
/// connecting. The key is generated by a controller over a secure session and expires
/// automatically after 32,767 increments of the global state number.
///
/// - SeeAlso: HAP Specification R2, Sections 7.4.7.3 – 7.4.7.4
public struct BLEBroadcastParameters: Equatable, Hashable, Sendable {

    /// Number of GSN increments after which a broadcast encryption key expires.
    public static let keyValidityPeriod: UInt32 = 32_767

    /// Size of the serialized storage representation in bytes.
    public static let storageSize = 2 + 32 + 1 + 6

    /// The global state number at which the key expires, or `nil` if no key is set.
    public private(set) var keyExpirationGSN: UInt16?

    /// The 32-byte broadcast encryption key, or `nil` if no key is set.
    public private(set) var key: Data?

    /// The 6-byte advertising identifier used in encrypted notification advertisements.
    ///
    /// When `nil`, the accessory's device ID is used.
    public var advertisingID: Data?

    /// Creates empty parameters, with no broadcast encryption key.
    public init() {
        self.keyExpirationGSN = nil
        self.key = nil
        self.advertisingID = nil
    }

    /// Whether a valid, unexpired broadcast encryption key is available at the given
    /// global state number.
    ///
    /// The key expires once the global state number passes its expiration value.
    public func hasValidKey(at gsn: UInt16) -> Bool {
        guard key != nil, let keyExpirationGSN else { return false }
        // The expiration wraps with the global state number, so a key is valid while the
        // distance from the current value to the expiration is within the validity period.
        let distance = UInt32(keyExpirationGSN) >= UInt32(gsn)
            ? UInt32(keyExpirationGSN) - UInt32(gsn)
            : UInt32(UInt16.max) - UInt32(gsn) + UInt32(keyExpirationGSN)
        return distance < Self.keyValidityPeriod
    }

    /// Generates a broadcast encryption key for a verified session.
    ///
    /// The key is derived with HKDF-SHA-512 from the session's Curve25519 shared secret,
    /// salted with the controller's Ed25519 long-term public key.
    ///
    /// - Parameters:
    ///   - sharedSecret: The Curve25519 shared secret established by Pair Verify.
    ///   - controllerPublicKey: The controller's Ed25519 long-term public key.
    ///   - gsn: The current global state number, from which the expiration is computed.
    ///   - crypto: The cryptographic provider.
    ///
    /// - SeeAlso: HAP Specification R2, Section 7.4.7.3 Broadcast Encryption Key Generation
    public mutating func generateKey<Crypto: CryptoProvider>(
        sharedSecret: Data,
        controllerPublicKey: Data,
        gsn: UInt16,
        using crypto: Crypto
    ) {
        self.key = crypto.hkdfSHA512(
            inputKeyMaterial: sharedSecret,
            salt: controllerPublicKey,
            info: Data(ascii: "Broadcast-Encryption-Key"),
            outputByteCount: 32
        )
        self.keyExpirationGSN = Self.expirationGSN(for: gsn)
    }

    /// Discards the broadcast encryption key.
    public mutating func removeKey() {
        self.key = nil
        self.keyExpirationGSN = nil
    }

    /// The global state number at which a key generated at `gsn` expires.
    ///
    /// The value wraps within the 1 – 65535 range of the global state number.
    static func expirationGSN(for gsn: UInt16) -> UInt16 {
        var expiration = UInt32(gsn) + Self.keyValidityPeriod - 1
        if expiration > UInt32(UInt16.max) {
            expiration -= UInt32(UInt16.max)
        }
        return UInt16(expiration)
    }
}

// MARK: - Storage Serialization

public extension BLEBroadcastParameters {

    /// Serializes the parameters in the ADK-compatible key-value store format:
    /// `keyExpirationGSN (2, little-endian) ‖ key (32) ‖ hasAdvertisingID (1) ‖ advertisingID (6)`.
    var storageData: Data {
        var bytes = littleEndianBytes(keyExpirationGSN ?? 0)
        bytes.append(contentsOf: key ?? Data([UInt8](repeating: 0, count: 32)))
        if let advertisingID, advertisingID.count == 6 {
            bytes.append(0x01)
            bytes.append(contentsOf: advertisingID)
        } else {
            bytes.append(0x00)
            bytes.append(contentsOf: [UInt8](repeating: 0, count: 6))
        }
        return Data(bytes)
    }

    /// Decodes parameters from their storage representation.
    init?(storageData: Data) {
        guard storageData.count == Self.storageSize else { return nil }
        let bytes = Array(storageData)
        self.init()
        let expiration = UInt16(bytes[0]) | UInt16(bytes[1]) << 8
        if expiration != 0 {
            self.keyExpirationGSN = expiration
            self.key = Data(bytes[2 ..< 34])
        }
        if bytes[34] == 0x01 {
            self.advertisingID = Data(bytes[35 ..< 41])
        }
    }
}
