
/// A HAP-BLE request PDU.
///
/// Wire format: `control (1) ‖ opcode (1) ‖ TID (1) ‖ instance ID (2, little-endian)`,
/// optionally followed by `body length (2, little-endian) ‖ body TLVs`.
///
/// - SeeAlso: HAP Specification R2, Section 7.3.3.2 HAP Request Format
public struct BLEPDURequest: Equatable, Hashable, Sendable {

    /// Size of the request PDU header in bytes.
    public static let headerSize = 5

    /// The HAP opcode.
    public var opcode: BLEPDUOpcode

    /// The transaction identifier, randomly generated by the originator.
    public var transactionID: UInt8

    /// The characteristic or service instance ID the request is directed at.
    public var instanceID: UInt16

    /// The body TLVs, if the PDU has a body.
    public var body: Data?

    public init(
        opcode: BLEPDUOpcode,
        transactionID: UInt8,
        instanceID: UInt16,
        body: Data? = nil
    ) {
        self.opcode = opcode
        self.transactionID = transactionID
        self.instanceID = instanceID
        self.body = body
    }

    /// Decodes an unfragmented (or reassembled) request PDU.
    public init(data: Data) throws(BLEPDUDecodeError) {
        let bytes = Array(data)
        guard bytes.count >= Self.headerSize else { throw .invalidFormat }
        let control = BLEPDUControlField(rawValue: bytes[0])
        guard control.isValid,
              !control.isContinuation,
              !control.usesExtendedInstanceIDs,
              control.pduType == .request
        else { throw .invalidFormat }
        let transactionID = bytes[2]
        guard let opcode = BLEPDUOpcode(rawValue: bytes[1]) else {
            throw .unsupportedOpcode(transactionID: transactionID)
        }
        self.opcode = opcode
        self.transactionID = transactionID
        self.instanceID = UInt16(bytes[3]) | UInt16(bytes[4]) << 8
        if bytes.count == Self.headerSize {
            self.body = nil
        } else {
            guard bytes.count >= Self.headerSize + 2 else { throw .invalidFormat }
            let bodyLength = Int(bytes[5]) | Int(bytes[6]) << 8
            guard bytes.count == Self.headerSize + 2 + bodyLength else { throw .invalidFormat }
            self.body = Data(bytes[(Self.headerSize + 2)...])
        }
    }

    /// The encoded, unfragmented PDU.
    public var data: Data {
        var bytes: [UInt8] = [
            BLEPDUControlField.request.rawValue,
            opcode.rawValue,
            transactionID,
            UInt8(truncatingIfNeeded: instanceID),
            UInt8(truncatingIfNeeded: instanceID >> 8)
        ]
        if let body {
            bytes.append(UInt8(truncatingIfNeeded: body.count))
            bytes.append(UInt8(truncatingIfNeeded: body.count >> 8))
            bytes.append(contentsOf: body)
        }
        return Data(bytes)
    }

    /// The encoded PDU, fragmented to the given maximum fragment size.
    public func fragments(maxFragmentSize: Int) -> [Data] {
        BLEPDUFragmentation.fragments(
            of: data,
            pduType: .request,
            transactionID: transactionID,
            maxFragmentSize: maxFragmentSize
        )
    }
}
